### ISSUE TITLE
Node on a Microsoft hosted agent

### ISSUE THREAD

**Issue by pedro-lima-jalafund** [fundev3/teamup-webapp#8]
#6 On azure pipelines file `task: NodeTool@0` is not necessary, according to [this](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#language-and-runtime).
The Microsoft hosted agent already comes with a version of node, as show [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software)

**Comment by martin-callejas-jalafund** [comment]
good catch, took me some minutes to fix my typos but in the end performance of the pipeline got a boost so we're good :rocket:
